version: '3'
services:
  my-active-directory__api:
    build: .
    image: registry.yuniq.agency/my-active-directory/my-active-directory-api-rec:latest
    ports:
      - '10053:3001'
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'

  my-active-directory__db:
    restart: unless-stopped
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data/

    logging:
      driver: 'json-file'
      options:
        max-size: '50m'

  my-active-directory__redis:
    restart: unless-stopped
    image: redis:alpine
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
    environment:
      REDIS_PASSWORD: ${REDIS_PASS}
    volumes:
      - ./redis:/data
